### ISSUE TITLE
please include Windows builds in the releases section

### ISSUE THREAD

**Issue by eladkarako** [MightyCreak/diffuse#144]

**Comment by MightyCreak** [comment]
I don't have Windows at home so this part needs someone to stand up and do the job. Any contribution in this area is **very** welcome!

**Comment by eladkarako** [comment]
me too, Linux is life.
I'll help, installing one from the ready to use VMs in https://developer.microsoft.com/en-gb/windows/downloads/virtual-machines/ shouldn't take too long.
I'll close it in few hours to keep me motivated ;)

**Comment by blackboxlogic** [comment]
I'm happy to help. I have no python experience and I've never setup a python build environment, but I bet it's within my reach.

Is lack of a build machine the only blocker? Are there other reasons this wouldn't build/run on Windows in it's current form?

**Comment by eladkarako** [comment]
Tried had some issues with building wheel for PyGObject under Windows.

tried installing it locally, then compiling it to exe similar to what is described on https://github.com/yt-dlp/yt-dlp#compile  

tried wrapping it as native python library/module with <a href="https://github.com/winpython/winpython/releases/download/4.6.20220116/Winpython32-3.10.2.0dot.exe  ">WinPython</a> similar to what I've done <a href="https://github.com/eladkarako/yt-dlp_kit">with yt-dlp</a>.

both cases had problem with building wheel for PyGObject. maybe it has issues with Python3 or Windows,  but since not even a clean Windows VM with Python3 and VS2019build-tools/VS2019 has managed to install it,  
so I've dropped it for now.

If anyone wants to try to wrap things,  
the details (above) should provide you a good starting point.

(b.t.w. this is not a `pip` installable package (no `setup.py`, or `pyproject.toml`), so just grab the zip from releases/latest).

**Comment by MightyCreak** [comment]
Since 0.4.8, there's been a few changes:
* Use GTK 3, instead of  GTK 2
* Python 3 support, instead of Python 2
* Split the code into several files, instead of one big monolithic file

I don't exactly know what is the appropriate way to port a Python GTK app to Windows. The overall idea is to "freeze" the scripts into an executable. Before, in version 0.4.8, it was using [py2exe](http://www.py2exe.org/). I kept the [`setup.py`](https://github.com/MightyCreak/diffuse/blob/master/windows-installer/setup.py) script, I'll remove it once a solution will be found to package a more recent version of Diffuse.

Once I did the migration to GTK 3, I tried to use [`cx_Freeze`](https://marcelotduarte.github.io/cx_Freeze/) but didn't succeed. My attempt are in another setup script: [setup.new.py](https://github.com/MightyCreak/diffuse/blob/master/windows-installer/setup.new.py).

It's important to note that when I tried to create an executable after the migration to GTK 3, I didn't know much about Python, GTK or the freeze process. Also, GTK 3 was more recent than it is today, maybe it has matured enough and it is easier now to port it to Windows.

If I were o test again, I would find another application written in Python, using GTK 3 and ported to Windows, and see how they are doing it. Another approach might be to create a package on [PyPI](https://pypi.org/). Anyway, I guess the first part of the investigation is to search the internets and ask around :wink:
