### ISSUE TITLE
Merge Documentation and Website

### ISSUE THREAD

**Issue by SlowMo24** [MightyCreak/diffuse#185]
Hi, thank you (all) for keeping this nice tool alive!

Do you think it would be a good idea to merge the documentation from https://github.com/MightyCreak/mightycreak.github.io/tree/master/diffuse into this repository to maintain all at one location? Especially with the installation and development docs being located here.

Also concerning documentation: is there an update schedule for the language files or is it fine to create a pull request with update-suggestions at any time?

**Comment by MightyCreak** [comment]
Thank you ;)

Might be interesting to merge the doc and the code together. I prefer to keep the two close together as much as possible.

I think it's been that way because of historical reasons. I've never thought about how I could merge both (or even if it's possible to host github pages a specific folder within a repo). Do you know if it's possible?

> Also concerning documentation: is there an update schedule for the language files or is it fine to create a pull request with update-suggestions at any time?

What do you mean exactly? Do you mean the language files like the programming language or the translation files?

**Comment by krlmlr** [comment]
Where does the new website live? https://mightycreak.github.io/diffuse doesn't show anything for me.

**Comment by MightyCreak** [comment]
Try again, it should be good now.

**Comment by MightyCreak** [comment]
BTW I created this issue #194 to merge the useful content from the old site to the new site. I just released 0.8.0, I can't spend more time on it right now, but it's a fairly simple task and if you were used to read it and find interesting documentation in the old website, please consider opening a PR and fixing this issue. Thanks :wink:
