### ISSUE TITLE
PPA for Ubuntu 20.04

### ISSUE THREAD

**Issue by likema** [MightyCreak/diffuse#36]
I built a PPA for diffuse Ubuntu 20.04:

https://launchpad.net/~likemartinma/+archive/ubuntu/diffuse?field.series_filter=focal

**Comment by likema** [comment]
Should I make PR for debian files?

**Comment by MightyCreak** [comment]
What do you mean exactly by that? I have a vague idea of what the debian files might be, but it would be nice if you could explain it to me ;)

**Comment by likema** [comment]
https://github.com/MightyCreak/diffuse/pull/38

This is what I mean.

**Comment by MightyCreak** [comment]
Thanks I'll take a look!

**Comment by MightyCreak** [comment]
Hi!

I've thought about it more and since I don't have a Debian machine and no knowledge of how to make a package for Debian, I'd rather not include Debian specific files, so I'll close this issue and the related PR.

That said, I would be interested to know how Debian packagers do in this (apparently common) situation? Do they have a separate repository? If they do, I would be willing to create a new one here dedicated for the Debian package of Diffuse.
